### PR TITLE
Correct piezo coordinates & nslices in AdjustedSpikes

### PR DESCRIPTION
**Pull request by olakiril**

### CODE REVIEW

**Comment by jakereimer** [comment]
shouldn't `uslices == 1:nslices` always?

**Comment by olakiril** [comment]
Not when you get single cells.

**Comment by jakereimer** [comment]
You mean there may be a slice without ROIs? Ok - I can see that.

**Comment by olakiril** [comment]
You can fetch the trace of just one cell or all the cells from one slice. uslices == 1:nslices  does not take that into account

**Pull request merged**
